#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FoodMate.Resource", IsApplication=true)]

namespace FoodMate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::FoodMate.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FoodMate.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FoodMate.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FoodMate.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_orange = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_settings = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_home = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_my_list = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_shopping_list = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon2 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int Barcode = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int Email = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int FirstName = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int GroupInfo = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int LastName = 2131165209;
			
			// aapt resource value: 0x7f07000e
			public const int ListView = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Name = 2131165199;
			
			// aapt resource value: 0x7f07001b
			public const int Phone = 2131165211;
			
			// aapt resource value: 0x7f070003
			public const int Price = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int addItem = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int addItemButton = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int btnLogin = 2131165201;
			
			// aapt resource value: 0x7f07001f
			public const int contentFrame = 2131165215;
			
			// aapt resource value: 0x7f070007
			public const int editItem = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int editItemButton = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int groupInfoText = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int itemInfoText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int itemName = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int itemPrice = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int itemQuantity = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int makePaymentButton = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int myListView = 2131165204;
			
			// aapt resource value: 0x7f07000b
			public const int pager = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int removeItem = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int requestItemButton = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int requestedListView = 2131165194;
			
			// aapt resource value: 0x7f07001c
			public const int settingsUpdate = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int shoppingListView = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int textView1 = 2131165214;
			
			// aapt resource value: 0x7f070010
			public const int txtvUserName = 2131165200;
			
			// aapt resource value: 0x7f070017
			public const int userInfoText = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int voteForItem = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int editItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int inventory = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItemRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int myList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int shoppingList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int tab = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int facebookLogin = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int library_name = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int tab1_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tab2_text = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
